AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Visitor Counter API

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs18.x

  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"



Resources:

  VisitorCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounter
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: visitor-counter/
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorCounterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCounterTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /visit
            Method: POST

Outputs:
  ApiUrl:
    Description: "Invoke URL for Visitor Count API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visit"
